apiVersion: apps/v1
kind: Deployment
metadata: 
    name: producer-deployment
    labels:
        app: producer
spec:
    replicas: 1
    selector:
        matchLabels:
            app: producer
    template:
        metadata:
            labels:
                app: producer
        spec:
            volumes:
                - name: task-pv-storage
                  persistentVolumeClaim:
                      claimName: task-pv-claim
            containers:
                - name: producer-deployment
                  image: gcr.io/cloudpoint-development/producer:v20
                  env:
                    - name: cacert
                      valueFrom:
                        secretKeyRef:
                          name: producer-secret
                          key: cacert
                    - name: producercert
                      valueFrom:
                        secretKeyRef:
                          name: producer-secret
                          key: producercert
                    - name: producerkey
                      valueFrom:
                        secretKeyRef:
                          name: producer-secret
                          key: producerkey
                    - name: hostname
                      value: 'rabbitmq-cluster-ip-service'
                  volumeMounts:
                    - name: task-pv-storage
                      mountPath: "/certificate/producer"
                      subPath: "producer-server-certificate"
                    - name: task-pv-storage
                      mountPath: "/certificate/CA"
                      subPath: "Trusted-CA"
                    - name: task-pv-storage
                      mountPath: "/usr/src/app/logs"
                      subPath: "logs"

            
